#!/bin/bash
#SET the web password from inside terraform
#user webuser
WEBPASS='myrandomstring!@!'
ADMINHOME="/home/admin"

# Ignore any intereactive dialog when doing upgrade
# sudo DEBIAN_FRONTEND=noninteractive sh -c 'echo $DEBIAN_FRONTEND'
sudo apt-get update
DEBIAN_FRONTEND=noninteractive apt-get upgrade -yq 

#install git
sudo apt install git -y

# work from the home directory and clone tpot
#cd $ADMINHOME
cd /tmp/
git clone https://github.com/telekom-security/tpotce.git

# make a copy of the default tpot.conf file. 
#cp ./tpotce/iso/installer/tpot.conf.dist ./tpot.conf
cp /tmp/tpotce/iso/installer/tpot.conf.dist /tmp/tpot.conf
# set the password to random string generated by terraform
sed "s/myCONF_WEB_PW[^ ]*/myCONF_WEB_PW='$WEBPASS'/g" -i /tmp/tpot.conf

cd /tmp/tpotce
sudo ./install.sh --type=auto --conf="/tmp/tpot.conf" &&
sudo systemctl start tpot
